name: GitHub Metrics e Spotify

on: 
  schedule:
    - cron: "0 * * * *" # executa a cada hora
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Estatísticas Gerais
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pammy-pw
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage, bytes
          plugin_languages_limit: 8

      - name: Spotify Plugin
        uses: lowlighter/metrics@latest
        with:
          filename: spotify-metrics.svg
          token: NOT_NEEDED
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
